---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[array_attr_test::default]
    provisioner:
      solo_rb:
        environment: test_env
      sudo: true
